# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zocom
# "service" is the name of this project. This will also be added to your AWS resource names.
service: jsonwebtoken-example

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::497180550327:role/lecture-role

functions:
  Login:
    handler: functions/Login/index.handler
    environment:
      SECRET: a1b1c1
    events:
      - httpApi:
          path: /auth/login
          method: post
  Signup:
    handler: functions/Signup/index.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
  GetUser:
    handler: functions/GetUser/index.handler
    environment:
      SECRET: a1b1c1
    events:
      - httpApi:
          path: /user
          method: get

resources:
  Resources:
    jwtAccounts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: jsonwebtoken-example
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
